# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-05 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumbb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumbb',
            new_name='thumb',
        ),
    ]
